### PR TITLE
make index.js and chrome run within a Docker container

### PR DESCRIPTION
**Pull request by mikemoraned**
- needed to change index.js to allow output to be saved in a
separate directory, so that this directory could be shared via
a volume

### CODE REVIEW

**Comment by mikemoraned** [comment]
note that I prove this worked as part of https://github.com/mikemoraned/shartan , using your install instructions as a base

**Review by dhurba87 — APPROVED** [review]

**Comment by mikemoraned** [comment]
@dhurba87 : need anything more from me, or you happy to merge? for example, should I bump the patch version in package.json?

**Comment by dhurba87** [comment]
`run.sh` file was not made executable in Dockerfile so I sent you a PR on your fork except for that, everything is working fine so I think this is great.
[PR](https://github.com/mikemoraned/chrome-headless-screenshots/pull/1)

**Comment by mikemoraned** [comment]
@dhurba87 : ok, I've merged your PR and collapsed the commits into my branch, so this *should* be  good to go.

**Comment by schnerd** [comment]
@mikemoraned this is awesome, thanks for the PR. everything looks good at a glance but I'm going to test it manually later today and confirm before merging 👍

**Comment by schnerd** [comment]
@mikemoraned 

```
$ docker run -it -v ${PWD}:/var/output/ --rm chrome-headless-screenshots-app --url="http://www.eff.org"
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
Screenshot saved
```

1. Passing the `--url` arg through the supplied `docker run` command doesn't seem to work correctly. output.png still shows up as google.com (which is the default page inside the script). I think in Dockerfile entrypoint you might want to use exec form instead of shell form, like `ENTRYPOINT ["./run.sh"]`. It started working for me after this change.

2. As you can see in the output, there is the following warning `libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted`. Are you seeing this when you test also? Doesn't seem to impact behavior but it's a bit concerning.

**Comment by mikemoraned** [comment]
@schnerd : re:

1. updated to use `ENTRYPOINT`
2. yes, I also see the `libudev ...` message, and it also has no apparent impact for me. Other usages of Chrome + Docker also see this problem e.g. see https://github.com/arachnys/athenapdf/blob/master/cli/docs/quick-start.md . I've added a section to README.md explaining it a little and recommending it is ignored.

btw, in case it becomes relevant my docker version is: `Docker version 17.06.0-ce, build 02c1d87` on MacOS X (`15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`)

**Comment by schnerd** [comment]
merged, thanks again!

**Pull request merged**
